# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - environment_setup/arm-templates/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - environment_setup/arm-templates/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devopsforai-aml-vg
  - name: WORKSPACE_SKU # https://docs.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-ml#sku
    value: basic

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: "$(RESOURCE_GROUP)"
    azureResourceManagerConnection: 'MSFT_AIA_account (2e187791-4e57-4e00-a4de-4b0cedde7ca5)'
    subscriptionId: '2e187791-4e57-4e00-a4de-4b0cedde7ca5'
    action: 'Create Or Update Resource Group'
    resourceGroupName: "$(RESOURCE_GROUP)"
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: "$(Build.SourcesDirectory)/environment_setup/arm-templates/cloud-environment.json"
    deploymentMode: 'Incremental'
